# Generated by Django 4.1.7 on 2023-06-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="과일", new_name="fruits",),
    ]
