# Generated by Django 4.1.7 on 2023-03-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmi',
            old_name='user_bim',
            new_name='user_bmi',
        ),
    ]
