# Generated by Django 4.1.7 on 2023-03-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wei', models.CharField(max_length=20)),
                ('cal', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
