# Generated by Django 4.1.7 on 2023-03-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_calorie_options_searchhistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calorie',
            table='food_cal',
        ),
    ]
